@AgentApi = http://localhost:5100

GET {{AgentApi}}/agents
Accept: application/json

###

POST {{AgentApi}}/agents
Accept: application/json
Content-Type: application/json

{
    "name": "New Agent 1",
    "agentType": 0,
    "description": "This is a description for New Agent 1"
}

###

GET {{AgentApi}}/agents/2457b6da-77ce-46bc-aaae-d59748ff2ec3
Accept: application/json

###

PUT {{AgentApi}}/agents/2457b6da-77ce-46bc-aaae-d59748ff2ec3
Accept: application/json
Content-Type: application/json

{
    "name": "Updated Agent Name",
    "agentType": 0,
    "description": "This is a description for New Agent 1"
}

###

PUT {{AgentApi}}/agents/2457b6da-77ce-46bc-aaae-d59748ff2ec3/ping
Accept: application/json
Content-Type: application/json

{
    "id": "2457b6da-77ce-46bc-aaae-d59748ff2ec3",
    "sentAt": "2025-05-11T15:00:00Z"
}

###