@AgentApi = http://localhost:5100

GET {{AgentApi}}/agents
Accept: application/json

###

POST {{AgentApi}}/agents
Accept: application/json
Content-Type: application/json

{
    "name": "New Agent 1"
}

###

GET {{AgentApi}}/agents/b394835f-ce35-4e6b-8cd7-7e553def2e23
Accept: application/json

###

PUT {{AgentApi}}/agents/b394835f-ce35-4e6b-8cd7-7e553def2e23
Accept: application/json
Content-Type: application/json

{
    "name": "Updated Agent Name"
}

###