@AgentApi = http://localhost:5010

### List Dispatches Filtered By Related Entity
GET {{AgentApi}}/dispatches/filtered?relatedEntityId=00000000-0000-0000-0000-000000000000
Accept: application/json

###

### Create Dispatch
POST {{AgentApi}}/dispatches
Content-Type: application/json

{
  "title": "System maintenance required",
  "description": "The system requires maintenance to ensure optimal performance at 29 July 2026 for 2 hours.",
  "category": 0,
  "occuredAt": "2026-06-10T08:00:00Z",
  "relatedEntityId": "00000000-0000-0000-0000-000000000000",
  "relatedChildEntityId": null,
  "providerAgentId": "3071ea39-56ef-42f8-a6fd-9f3d3b4ebdf6"
}

###

### Update Dispatch
PUT {{AgentApi}}/dispatches/00000000-0000-0000-0000-000000000000
Content-Type: application/json

{
  "title": "System maintenance required — updated",
  "description": "The system requires maintenance to ensure optimal performance at 29 July 2026 for 2 hours.",
  "category": 0,
  "occuredAt": "2026-06-10T08:30:00Z",
  "relatedEntityId": "00000000-0000-0000-0000-000000000000",
  "relatedChildEntityId": null,
  "providerAgentId": "3071ea39-56ef-42f8-a6fd-9f3d3b4ebdf6"
}

###

### Delete Dispatch
DELETE {{AgentApi}}/dispatches/00000000-0000-0000-0000-000000000000
Accept: application/json

###
