@AgentApi = http://localhost:5100

### List All Operations
GET {{AgentApi}}/operations
Accept: application/json

###

### Create Operation
POST {{AgentApi}}/operations
Content-Type: application/json

{
  "name": "Operation Hammer",
  "description": "Intercept and neutralize unauthorized aerial threats in sector north east.",
  "startDate": "2026-05-10T08:00:00Z",
  "estimatedEndDate": "2026-05-15T18:00:00Z",
  "operationStatus": 0,
  "operationType": 0
}

###

### Get Operation By Id | Seed value
GET {{AgentApi}}/operations/a394835f-ce35-4e6b-8cd7-7e553def2e44
Accept: application/json

###

### Get Operation By Id
GET {{AgentApi}}/operations/bc306839-b4a0-4525-9589-31eb7aed1e80
Accept: application/json

###

### Create Operation
POST {{AgentApi}}/operations/assets
Content-Type: application/json

{
  "operationId": "bc306839-b4a0-4525-9589-31eb7aed1e80",
  "assetId": "c394835f-ce35-4e6b-8cd7-7e553def2e25"
}
