global using OpenCMS.CMS.Application.Configurations;
global using OpenCMS.CMS.Domain.Entities;
global using MediatR;
global using System.Collections.Generic;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.AspNetCore.Builder;
