@AgentApi = http://localhost:5100

GET {{AgentApi}}/agents
Accept: application/json

###

POST {{AgentApi}}/agents
Accept: application/json
Content-Type: application/json

{
    "name": "New Agent 1"
}

###

GET {{AgentApi}}/agents/bddaacc6-e3f6-4f72-9549-4b5f3678b6ad
Accept: application/json

###