@AgentApi = http://localhost:5100

GET {{AgentApi}}/agents
Accept: application/json

###

POST {{AgentApi}}/agents
Accept: application/json
Content-Type: application/json

{
    "name": "OLD Agent "
}

###
